repos:
-   repo: https://github.com/Jeffresh/deployment-of-machine-learning-models
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8